name       : docker-machine
version    : 0.13.0
release    : 4
source     :
    - https://github.com/docker/machine/archive/v0.13.0.tar.gz : f75f6602a6d013a7b2ae517c3bdb07d8977825c1a0506157831fcd2ae083dc25
license    : Apache-2.0
component  : system.utils
summary    : Machine management for a container-centric world
description: |
    Machine management for a container-centric world
extract    : no
networking : yes
builddeps  :
    - git
    - golang
setup      : |
    mkdir -p goworkspace/src/github.com/docker
    tar -xf $sources/v$version.tar.gz -C goworkspace/src/github.com/docker
    mv goworkspace/src/github.com/docker/machine-$version \
        goworkspace/src/github.com/docker/machine
build      : |
    export GOPATH=$workdir
    cd src/github.com/docker/machine
    go get github.com/codegangsta/cli
    %make build
install    : |
    cd src/github.com/docker/machine
    install -Dm00755 bin/docker-machine $installdir/usr/bin/docker-machine
